/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as RoboticsRouteImport } from './routes/robotics'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProductsOjasRouteImport } from './routes/products.ojas'
import { Route as ProductsParthRouteImport } from './routes/products.parth'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const RoboticsRoute = RoboticsRouteImport.update({
  id: '/robotics',
  path: '/robotics',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsOjasRoute = ProductsOjasRouteImport.update({
  id: '/products/ojas',
  path: '/products/ojas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsParthRoute = ProductsParthRouteImport.update({
  id: '/products/parth',
  path: '/products/parth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/intelligence': typeof IntelligenceRoute
  '/privacy': typeof PrivacyRoute
  '/research': typeof ResearchRoute
  '/robotics': typeof RoboticsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/products/ojas': typeof ProductsOjasRoute
  '/products/parth': typeof ProductsParthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/intelligence': typeof IntelligenceRoute
  '/privacy': typeof PrivacyRoute
  '/research': typeof ResearchRoute
  '/robotics': typeof RoboticsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/products/ojas': typeof ProductsOjasRoute
  '/products/parth': typeof ProductsParthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/intelligence': typeof IntelligenceRoute
  '/privacy': typeof PrivacyRoute
  '/research': typeof ResearchRoute
  '/robotics': typeof RoboticsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/products/ojas': typeof ProductsOjasRoute
  '/products/parth': typeof ProductsParthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/company'
    | '/contact'
    | '/intelligence'
    | '/privacy'
    | '/research'
    | '/robotics'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/products/ojas'
    | '/products/parth'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company'
    | '/contact'
    | '/intelligence'
    | '/privacy'
    | '/research'
    | '/robotics'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/products/ojas'
    | '/products/parth'
  id:
    | '__root__'
    | '/'
    | '/company'
    | '/contact'
    | '/intelligence'
    | '/privacy'
    | '/research'
    | '/robotics'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/products/ojas'
    | '/products/parth'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyRoute: typeof CompanyRoute
  ContactRoute: typeof ContactRoute
  IntelligenceRoute: typeof IntelligenceRoute
  PrivacyRoute: typeof PrivacyRoute
  ResearchRoute: typeof ResearchRoute
  RoboticsRoute: typeof RoboticsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ProductsOjasRoute: typeof ProductsOjasRoute
  ProductsParthRoute: typeof ProductsParthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robotics': {
      id: '/robotics'
      path: '/robotics'
      fullPath: '/robotics'
      preLoaderRoute: typeof RoboticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/ojas': {
      id: '/products/ojas'
      path: '/products/ojas'
      fullPath: '/products/ojas'
      preLoaderRoute: typeof ProductsOjasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/parth': {
      id: '/products/parth'
      path: '/products/parth'
      fullPath: '/products/parth'
      preLoaderRoute: typeof ProductsParthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyRoute: CompanyRoute,
  ContactRoute: ContactRoute,
  IntelligenceRoute: IntelligenceRoute,
  PrivacyRoute: PrivacyRoute,
  ResearchRoute: ResearchRoute,
  RoboticsRoute: RoboticsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ProductsOjasRoute: ProductsOjasRoute,
  ProductsParthRoute: ProductsParthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
